<?php

declare(strict_types=1);

/**
 * International dial codes for phone prefix selects (ISO 3166-1 alpha-2 + E.164 prefix).
 *
 * @return list<array{iso:string,dial:string,name:string}>
 */
return [
    ['iso' => 'IT', 'dial' => '39', 'name' => 'Italia'],
    ['iso' => 'DE', 'dial' => '49', 'name' => 'Deutschland'],
    ['iso' => 'AT', 'dial' => '43', 'name' => 'Österreich'],
    ['iso' => 'CH', 'dial' => '41', 'name' => 'Schweiz'],
    ['iso' => 'FR', 'dial' => '33', 'name' => 'France'],
    ['iso' => 'ES', 'dial' => '34', 'name' => 'España'],
    ['iso' => 'PT', 'dial' => '351', 'name' => 'Portugal'],
    ['iso' => 'GB', 'dial' => '44', 'name' => 'United Kingdom'],
    ['iso' => 'IE', 'dial' => '353', 'name' => 'Ireland'],
    ['iso' => 'NL', 'dial' => '31', 'name' => 'Nederland'],
    ['iso' => 'BE', 'dial' => '32', 'name' => 'België / Belgique'],
    ['iso' => 'LU', 'dial' => '352', 'name' => 'Luxembourg'],
    ['iso' => 'PL', 'dial' => '48', 'name' => 'Polska'],
    ['iso' => 'CZ', 'dial' => '420', 'name' => 'Česko'],
    ['iso' => 'SK', 'dial' => '421', 'name' => 'Slovensko'],
    ['iso' => 'HU', 'dial' => '36', 'name' => 'Magyarország'],
    ['iso' => 'RO', 'dial' => '40', 'name' => 'România'],
    ['iso' => 'BG', 'dial' => '359', 'name' => 'Bulgaria'],
    ['iso' => 'GR', 'dial' => '30', 'name' => 'Ελλάδα'],
    ['iso' => 'HR', 'dial' => '385', 'name' => 'Hrvatska'],
    ['iso' => 'SI', 'dial' => '386', 'name' => 'Slovenija'],
    ['iso' => 'RS', 'dial' => '381', 'name' => 'Srbija'],
    ['iso' => 'BA', 'dial' => '387', 'name' => 'Bosna i Hercegovina'],
    ['iso' => 'ME', 'dial' => '382', 'name' => 'Crna Gora'],
    ['iso' => 'MK', 'dial' => '389', 'name' => 'North Macedonia'],
    ['iso' => 'AL', 'dial' => '355', 'name' => 'Shqipëri'],
    ['iso' => 'SE', 'dial' => '46', 'name' => 'Sverige'],
    ['iso' => 'NO', 'dial' => '47', 'name' => 'Norge'],
    ['iso' => 'DK', 'dial' => '45', 'name' => 'Danmark'],
    ['iso' => 'FI', 'dial' => '358', 'name' => 'Suomi'],
    ['iso' => 'IS', 'dial' => '354', 'name' => 'Ísland'],
    ['iso' => 'EE', 'dial' => '372', 'name' => 'Eesti'],
    ['iso' => 'LV', 'dial' => '371', 'name' => 'Latvija'],
    ['iso' => 'LT', 'dial' => '370', 'name' => 'Lietuva'],
    ['iso' => 'UA', 'dial' => '380', 'name' => 'Україна'],
    ['iso' => 'MD', 'dial' => '373', 'name' => 'Moldova'],
    ['iso' => 'BY', 'dial' => '375', 'name' => 'Беларусь'],
    ['iso' => 'RU', 'dial' => '7', 'name' => 'Россия'],
    ['iso' => 'TR', 'dial' => '90', 'name' => 'Türkiye'],
    ['iso' => 'US', 'dial' => '1', 'name' => 'United States'],
    ['iso' => 'CA', 'dial' => '1', 'name' => 'Canada'],
    ['iso' => 'MX', 'dial' => '52', 'name' => 'México'],
    ['iso' => 'BR', 'dial' => '55', 'name' => 'Brasil'],
    ['iso' => 'AR', 'dial' => '54', 'name' => 'Argentina'],
    ['iso' => 'CL', 'dial' => '56', 'name' => 'Chile'],
    ['iso' => 'CO', 'dial' => '57', 'name' => 'Colombia'],
    ['iso' => 'PE', 'dial' => '51', 'name' => 'Perú'],
    ['iso' => 'AU', 'dial' => '61', 'name' => 'Australia'],
    ['iso' => 'NZ', 'dial' => '64', 'name' => 'New Zealand'],
    ['iso' => 'JP', 'dial' => '81', 'name' => '日本'],
    ['iso' => 'CN', 'dial' => '86', 'name' => '中国'],
    ['iso' => 'KR', 'dial' => '82', 'name' => '대한민국'],
    ['iso' => 'IN', 'dial' => '91', 'name' => 'India'],
    ['iso' => 'SG', 'dial' => '65', 'name' => 'Singapore'],
    ['iso' => 'HK', 'dial' => '852', 'name' => 'Hong Kong'],
    ['iso' => 'TW', 'dial' => '886', 'name' => 'Taiwan'],
    ['iso' => 'AE', 'dial' => '971', 'name' => 'United Arab Emirates'],
    ['iso' => 'SA', 'dial' => '966', 'name' => 'Saudi Arabia'],
    ['iso' => 'IL', 'dial' => '972', 'name' => 'Israel'],
    ['iso' => 'EG', 'dial' => '20', 'name' => 'Egypt'],
    ['iso' => 'ZA', 'dial' => '27', 'name' => 'South Africa'],
    ['iso' => 'MA', 'dial' => '212', 'name' => 'Maroc'],
    ['iso' => 'TN', 'dial' => '216', 'name' => 'Tunisie'],
];
